POST http://localhost:3000/register
Content-Type: application/json

{
  "email" : "chris@assembler.com",
  "name" : "Chris",
  "password" : "123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "chris@assembler.com",
  "password" : "123456"
}


###
GET http://localhost:3000/api/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjAzNDY0NTAzfQ.TtCQIKbNWZwGa3VTx-rZRt-ABpt-b5EjXrTxakZJTU4

###
GET http://localhost:3000/api/coins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjAzNDY0NTAzfQ.TtCQIKbNWZwGa3VTx-rZRt-ABpt-b5EjXrTxakZJTU4

###
GET http://localhost:3000/api/wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjAzNTcxODUwfQ.68dnXn4yE_UcdGEXWabte74IeCC6VshyYvDfT6OQLZQ