POST http://localhost:3000/register
Content-Type: application/json

{
  "email" : "chris@assembler.com",
  "name" : "Chris",
  "password" : "123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "admin",
  "password" : "admin"
}

###
GET http://localhost:3000/api/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAzNTc2OTQwfQ.A_cAT3rEgcVyuVmrRpXcKqnyLoe02wjj4u8aNUYHU10

###
GET http://localhost:3000/api/wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAzNTc2OTQwfQ.A_cAT3rEgcVyuVmrRpXcKqnyLoe02wjj4u8aNUYHU10

###
POST http://localhost:3000/api/buy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAzNTc2OTQwfQ.A_cAT3rEgcVyuVmrRpXcKqnyLoe02wjj4u8aNUYHU10
Content-Type: application/json

{
  "symbol" : "BTC",
  "quantity": "1"
}

###
POST http://localhost:3000/api/sell
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAzNTc2OTQwfQ.A_cAT3rEgcVyuVmrRpXcKqnyLoe02wjj4u8aNUYHU10
Content-Type: application/json

{
  "symbol" : "TRX",
  "quantity": "10000"
}
